# Generated by Django 4.1 on 2022-11-24 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodeguero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('SKU', models.CharField(max_length=30, unique=True)),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('cod_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('faltante', models.IntegerField(blank=True, default=0, null=True)),
                ('vendido', models.IntegerField(blank=True, default=0, null=True)),
                ('descuento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_unitario', models.CharField(blank=True, max_length=50, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstApp.categoria')),
            ],
        ),
    ]
